theme: jekyll-theme-cayman
title: WindPulse
description: Heat Map-Based Clustered Diurnal Wind Power Density Analysis for Optimized Maintenance Scheduling of Wind Farms in India
show_downloads: true
google_analytics: 
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
